service: dat2ohanasi-backend

plugins:
  # - serverless-domain-manager

custom:
  defaultStage: dev
  api_version: v0
  common: common # serverless.ymlのバグ回避用
  customDomain:
    stage: ${self:provider.stage}
    createRoute53Record: true


provider:
  name: aws
  runtime: provided
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: qazx7412
  environment:
    ${file(./env.yml)}

functions:
  hello:
    handler: dat2ohanasi
    events:
      - http:
          path: ohanasi
          method: get
          integration: lambda
